syntax = "proto3";
package org.solana.sealevel.v1;

message QuicClose {
    uint32 connection_id = 1;
}

message QuicConnect {
    uint32 connection_id = 1;
}

message QuicSend {
    uint32 connection_id = 1;
    uint32 payload_sz = 2;
}

message QuicService {
    uint32 connection_id = 1;
}

message QuicMsg {
    oneof message_type {
        QuicConnect connect = 1;
        QuicClose close = 2;
        QuicSend send = 3;
        QuicService service = 4;
    }
    bytes buffer = 5;
}

message QuicInputMsg {
    repeated QuicMsg messages = 1;
}

message QuicOutput {
    uint32 connection_id = 1;
}
